logging:
  level:
    org.springframework.web: DEBUG
    org.springframework.web.servlet.mvc.method.annotation: TRACE
    org:
      hibernate:
        SQL=DEBUG:
        orm:
          JDBC:
            bind=TRACE:
spring:
  application:
    name: eCommerce

  h2:
    console:
      enabled: true

  datasource:
    url: jdbc:h2:mem:test

  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update